###
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6Ik1pa2hhaWwiLCJlbWFpbCI6InRlc3QwQHRlc3QuY29tIiwiaWF0IjoxNzcyMjAyMjQ4LCJleHAiOjE3NzIyMDU4NDh9.solYmAiOaoplyMQMnkUQacsZwy4KycC8qxwurQdgDcs

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Mikhail",
    "email": "test23@test.com",
    "password": "123456"
}



###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test8@test.com",
    "password": "123456"
}



###
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJNaWtoYWlsIiwiZW1haWwiOiJ0ZXN0OEB0ZXN0LmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzcyMjM0NTU3LCJleHAiOjE3NzIzMjA5NTd9.qrwVXEdc6mCaPoIphL1ZbRuJvgz-v9CsdKraPCCgD70

{
    "name": "Gray T-shirt",
    "description": "Just a Gray T-shirt",
    "price": 10,
    "imageUrl": ""

}
